import { defineConfig } from "oxlint";

export const native = defineConfig({
  plugins: [
    "typescript",
    "import",
    "react",
    "unicorn",
  ],
  categories: {
    correctness: "error",
  },
  options: {
    reportUnusedDisableDirectives: "error",
    typeAware                    : true,
  },
  env: {
    builtin: true,
    es2026 : true,
    node   : true,
  },
  rules: {
    "constructor-super"            : "error",
    "for-direction"                : "error",
    "getter-return"                : "error",
    "no-async-promise-executor"    : "error",
    "no-case-declarations"         : "error",
    "no-class-assign"              : "error",
    "no-compare-neg-zero"          : "error",
    "no-cond-assign"               : "error",
    "no-const-assign"              : "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition"        : "error",
    "no-control-regex"             : "error",
    "no-debugger"                  : "error",
    "no-delete-var"                : "error",
    "no-dupe-class-members"        : "error",
    "no-dupe-else-if"              : "error",
    "no-dupe-keys"                 : "error",
    "no-duplicate-case"            : "error",
    "no-empty"                     : "error",
    "no-empty-character-class"     : "error",
    "no-empty-pattern"             : "error",
    "no-empty-static-block"        : "error",
    "no-ex-assign"                 : "error",
    "no-extra-boolean-cast"        : "error",
    "no-fallthrough"               : [
      "error",
      {
        allowEmptyCase                : true,
        commentPattern                : String.raw`falls?\s?through`,
        reportUnusedFallthroughComment: true,
      },
    ],
    "no-func-assign"               : "error",
    "no-global-assign"             : "error",
    "no-import-assign"             : "error",
    "no-invalid-regexp"            : "error",
    "no-irregular-whitespace"      : "error",
    "no-loss-of-precision"         : "error",
    "no-misleading-character-class": "error",
    "no-new-native-nonconstructor" : "error",
    "no-nonoctal-decimal-escape"   : "error",
    "no-obj-calls"                 : "error",
    "no-prototype-builtins"        : "error",
    "no-redeclare"                 : "error",
    "no-regex-spaces"              : "error",
    "no-self-assign"               : "error",
    "no-setter-return"             : "error",
    "no-shadow-restricted-names"   : "error",
    "no-sparse-arrays"             : "error",
    "no-this-before-super"         : "error",
    "no-unassigned-vars"           : "error",
    "no-undef"                     : "error",
    "no-unexpected-multiline"      : "error",
    "no-unreachable"               : "error",
    "no-unsafe-finally"            : "error",
    "no-unsafe-negation"           : "error",
    "no-unsafe-optional-chaining"  : "error",
    "no-unused-labels"             : "error",
    "no-unused-vars"               : "error",
    "no-useless-assignment"        : "error",
    "no-useless-backreference"     : "error",
    "no-useless-catch"             : "error",
    "no-useless-escape"            : "error",
    "no-with"                      : "error",
    "preserve-caught-error"        : "error",
    "require-yield"                : "error",
    "use-isnan"                    : "error",
    "valid-typeof"                 : "error",
    "array-callback-return"        : [
      "error",
      {
        allowVoid: true,
      },
    ],
    "no-await-in-loop"     : "error",
    "no-constructor-return": "error",
    "no-duplicate-imports" : [
      "error",
      {
        includeExports: true,
      },
    ],
    "no-promise-executor-return"  : "error",
    "no-self-compare"             : "error",
    "no-template-curly-in-string" : "error",
    "no-unmodified-loop-condition": "error",
    "no-use-before-define"        : "error",
    "arrow-body-style"            : [
      "error",
      "as-needed",
    ],
    "class-methods-use-this": "error",
    "curly"                 : [
      "error",
      "multi-or-nest",
      "consistent",
    ],
    "default-case"      : "error",
    "default-case-last" : "error",
    "default-param-last": "error",
    "eqeqeq"            : [
      "error",
      "always",
      {
        null: "ignore",
      },
    ],
    "func-name-matching": [
      "error",
      "always",
      {
        considerPropertyDescriptor: true,
      },
    ],
    "func-names": [
      "error",
      "always",
    ],
    "func-style": [
      "error",
      "declaration",
      {
        allowArrowFunctions: true,
      },
    ],
    "grouped-accessor-pairs": [
      "error",
      "getBeforeSet",
    ],
    "guard-for-in"                : "error",
    "logical-assignment-operators": [
      "error",
      "always",
      {
        enforceForIfStatements: true,
      },
    ],
    "max-classes-per-file": [
      "error",
      {
        ignoreExpressions: true,
        max              : 1,
      },
    ],
    "max-depth": [
      "error",
      {
        max: 4,
      },
    ],
    "max-nested-callbacks": [
      "error",
      {
        max: 3,
      },
    ],
    "max-params": [
      "error",
      {
        max: 3,
      },
    ],
    "new-cap": [
      "error",
      {
        newIsCap  : true,
        capIsNew  : false,
        properties: true,
      },
    ],
    "no-array-constructor": "error",
    "no-caller"           : "error",
    "no-console"          : [
      "error",
      {
        allow: [
          "info",
          "warn",
          "error",
        ],
      },
    ],
    "no-div-regex"  : "error",
    "no-else-return": [
      "error",
      {
        allowElseIf: false,
      },
    ],
    "no-empty-function"  : "error",
    "no-eval"            : "error",
    "no-extra-bind"      : "error",
    "no-extra-label"     : "error",
    "no-implicit-globals": "error",
    "no-implied-eval"    : "error",
    "no-iterator"        : "error",
    "no-label-var"       : "error",
    "no-lone-blocks"     : "error",
    "no-lonely-if"       : "error",
    "no-magic-numbers"   : [
      "error",
      {
        ignore                       : [...new Set(Array.from({ length: 11 }).flatMap((_, index) => [index, +`-${ index }`, `${ index }n`, `-${ index }n`]))],
        ignoreDefaultValues          : true,
        ignoreEnums                  : true,
        ignoreNumericLiteralTypes    : true,
        ignoreReadonlyClassProperties: true,
      },
    ],
    "no-multi-assign": [
      "error",
      {
        ignoreNonDeclaration: true,
      },
    ],
    "no-multi-str"         : "error",
    "no-negated-condition" : "error",
    "no-new-func"          : "error",
    "no-object-constructor": "error",
    "no-proto"             : "error",
    "no-return-assign"     : "error",
    "no-script-url"        : "error",
    "no-sequences"         : "error",
    "no-shadow"            : "error",
    "no-undefined"         : "error",
    "no-underscore-dangle" : [
      "error",
      {
        allowAfterThis           : true,
        allowAfterSuper          : true,
        allowAfterThisConstructor: true,
        allowFunctionParams      : false,
      },
    ],
    "no-unneeded-ternary"    : "error",
    "no-useless-computed-key": [
      "error",
      {
        enforceForClassMembers: true,
      },
    ],
    "no-useless-concat"     : "error",
    "no-useless-constructor": "error",
    "no-useless-rename"     : "error",
    "no-useless-return"     : "error",
    "no-var"                : "error",
    "operator-assignment"   : "error",
    "prefer-arrow-callback" : [
      "error",
      {
        allowNamedFunctions: true,
      },
    ],
    "prefer-const": [
      "error",
      {
        destructuring: "all",
      },
    ],
    "prefer-exponentiation-operator": "error",
    "prefer-numeric-literals"       : "error",
    "prefer-object-has-own"         : "error",
    "prefer-object-spread"          : "error",
    "prefer-promise-reject-errors"  : "error",
    "prefer-regex-literals"         : [
      "error",
      {
        disallowRedundantWrapping: true,
      },
    ],
    "prefer-rest-params": "error",
    "prefer-template"   : "error",
    "radix"             : [
      "error",
      "as-needed",
    ],
    "yoda": [
      "error",
      "never",
      {
        exceptRange: true,
      },
    ],
    "unicode-bom"                      : "error",
    "import/namespace"                 : "error",
    "import/default"                   : "error",
    "import/export"                    : "error",
    "import/no-named-as-default"       : "error",
    "import/no-named-as-default-member": "error",
    "import/no-duplicates"             : [
      "error",
      {
        considerQueryString: true,
      },
    ],
    "import/no-absolute-path"    : "error",
    "import/no-cycle"            : "error",
    "import/no-named-default"    : "error",
    "import/no-self-import"      : "error",
    "import/first"               : "error",
    "import/exports-last"        : "error",
    "import/newline-after-import": [
      "error",
      {
        count: 1,
      },
    ],
    "react/jsx-curly-brace-presence": [
      "error",
      {
        propElementValues: "always",
      },
    ],
    "react/jsx-pascal-case"  : "error",
    "react/self-closing-comp": [
      "error",
      {
        component: true,
        html     : true,
      },
    ],
    "unicorn/catch-error-name"                : "error",
    "unicorn/consistent-assert"               : "error",
    "unicorn/consistent-date-clone"           : "error",
    "unicorn/consistent-empty-array-spread"   : "error",
    "unicorn/consistent-existence-index-check": "error",
    "unicorn/consistent-function-scoping"     : "error",
    "unicorn/custom-error-definition"         : "error",
    "unicorn/empty-brace-spaces"              : "error",
    "unicorn/error-message"                   : "error",
    "unicorn/escape-case"                     : "error",
    "unicorn/explicit-length-check"           : "error",
    "unicorn/filename-case"                   : [
      "error",
      {
        case                  : "kebabCase",
        multipleFileExtensions: false,
      },
    ],
    "unicorn/new-for-builtins"                       : "error",
    "unicorn/no-abusive-eslint-disable"              : "error",
    "unicorn/no-accessor-recursion"                  : "error",
    "unicorn/no-anonymous-default-export"            : "error",
    "unicorn/no-array-for-each"                      : "error",
    "unicorn/no-array-method-this-argument"          : "error",
    "unicorn/no-array-reverse"                       : "error",
    "unicorn/no-array-sort"                          : "error",
    "unicorn/no-await-expression-member"             : "error",
    "unicorn/no-await-in-promise-methods"            : "error",
    "unicorn/no-console-spaces"                      : "error",
    "unicorn/no-document-cookie"                     : "error",
    "unicorn/no-empty-file"                          : "error",
    "unicorn/no-hex-escape"                          : "error",
    "unicorn/no-immediate-mutation"                  : "error",
    "unicorn/no-instanceof-builtins"                 : "error",
    "unicorn/no-invalid-fetch-options"               : "error",
    "unicorn/no-invalid-remove-event-listener"       : "error",
    "unicorn/no-lonely-if"                           : "error",
    "unicorn/no-negated-condition"                   : "error",
    "unicorn/no-negation-in-equality-check"          : "error",
    "unicorn/no-new-array"                           : "error",
    "unicorn/no-new-buffer"                          : "error",
    "unicorn/no-process-exit"                        : "error",
    "unicorn/no-single-promise-in-promise-methods"   : "error",
    "unicorn/no-static-only-class"                   : "error",
    "unicorn/no-typeof-undefined"                    : "error",
    "unicorn/no-unnecessary-array-flat-depth"        : "error",
    "unicorn/no-unnecessary-array-splice-count"      : "error",
    "unicorn/no-unnecessary-await"                   : "error",
    "unicorn/no-unnecessary-slice-end"               : "error",
    "unicorn/no-unreadable-array-destructuring"      : "error",
    "unicorn/no-unreadable-iife"                     : "error",
    "unicorn/no-useless-collection-argument"         : "error",
    "unicorn/no-useless-error-capture-stack-trace"   : "error",
    "unicorn/no-useless-length-check"                : "error",
    "unicorn/no-useless-promise-resolve-reject"      : "error",
    "unicorn/no-useless-spread"                      : "error",
    "unicorn/no-useless-switch-case"                 : "error",
    "unicorn/no-useless-undefined"                   : "error",
    "unicorn/no-zero-fractions"                      : "error",
    "unicorn/number-literal-case"                    : "error",
    "unicorn/numeric-separators-style"               : "error",
    "unicorn/prefer-add-event-listener"              : "error",
    "unicorn/prefer-array-find"                      : "error",
    "unicorn/prefer-array-flat-map"                  : "error",
    "unicorn/prefer-array-flat"                      : "error",
    "unicorn/prefer-array-index-of"                  : "error",
    "unicorn/prefer-array-some"                      : "error",
    "unicorn/prefer-at"                              : "error",
    "unicorn/prefer-bigint-literals"                 : "error",
    "unicorn/prefer-blob-reading-methods"            : "error",
    "unicorn/prefer-class-fields"                    : "error",
    "unicorn/prefer-classlist-toggle"                : "error",
    "unicorn/prefer-code-point"                      : "error",
    "unicorn/prefer-date-now"                        : "error",
    "unicorn/prefer-default-parameters"              : "error",
    "unicorn/prefer-dom-node-append"                 : "error",
    "unicorn/prefer-dom-node-remove"                 : "error",
    "unicorn/prefer-export-from"                     : ["error", { checkUsedVariables: true }],
    "unicorn/prefer-global-this"                     : "error",
    "unicorn/prefer-import-meta-properties"          : "error",
    "unicorn/prefer-includes"                        : "error",
    "unicorn/prefer-keyboard-event-key"              : "error",
    "unicorn/prefer-logical-operator-over-ternary"   : "error",
    "unicorn/prefer-math-min-max"                    : "error",
    "unicorn/prefer-math-trunc"                      : "error",
    "unicorn/prefer-modern-dom-apis"                 : "error",
    "unicorn/prefer-modern-math-apis"                : "error",
    "unicorn/prefer-module"                          : "error",
    "unicorn/prefer-native-coercion-functions"       : "error",
    "unicorn/prefer-negative-index"                  : "error",
    "unicorn/prefer-node-protocol"                   : "error",
    "unicorn/prefer-number-properties"               : "error",
    "unicorn/prefer-object-from-entries"             : "error",
    "unicorn/prefer-optional-catch-binding"          : "error",
    "unicorn/prefer-prototype-methods"               : "error",
    "unicorn/prefer-query-selector"                  : "error",
    "unicorn/prefer-reflect-apply"                   : "error",
    "unicorn/prefer-regexp-test"                     : "error",
    "unicorn/prefer-response-static-json"            : "error",
    "unicorn/prefer-set-has"                         : "error",
    "unicorn/prefer-set-size"                        : "error",
    "unicorn/prefer-spread"                          : "error",
    "unicorn/prefer-string-raw"                      : "error",
    "unicorn/prefer-string-replace-all"              : "error",
    "unicorn/prefer-string-slice"                    : "error",
    "unicorn/prefer-string-starts-ends-with"         : "error",
    "unicorn/prefer-string-trim-start-end"           : "error",
    "unicorn/prefer-structured-clone"                : "error",
    "unicorn/prefer-ternary"                         : "error",
    "unicorn/prefer-type-error"                      : "error",
    "unicorn/require-array-join-separator"           : "error",
    "unicorn/require-module-attributes"              : "error",
    "unicorn/require-module-specifiers"              : "error",
    "unicorn/require-number-to-fixed-digits-argument": "error",
    "unicorn/require-post-message-target-origin"     : "error",
    "unicorn/text-encoding-identifier-case"          : "error",
    "unicorn/throw-new-error"                        : "error",
    "no-unused-expressions"                          : "error",
    "typescript/consistent-return"                   : "error",
    "typescript/dot-notation"                        : "error",
    "typescript/ban-ts-comment"                      : [
      "error",
      {
        "ts-expect-error": "allow-with-description",
      },
    ],
    "typescript/no-deprecated"           : "error",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-empty-object-type"    : [
      "error",
      {
        allowInterfaces: "with-single-extends",
      },
    ],
    "typescript/no-explicit-any"                    : "error",
    "typescript/no-extra-non-null-assertion"        : "error",
    "typescript/no-misused-new"                     : "error",
    "typescript/no-namespace"                       : "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-require-imports"                 : "error",
    "typescript/no-this-alias"                      : "error",
    "typescript/no-unnecessary-type-constraint"     : "error",
    "typescript/no-unsafe-declaration-merging"      : "error",
    "typescript/no-unsafe-function-type"            : "error",
    "typescript/no-wrapper-object-types"            : "error",
    "typescript/prefer-as-const"                    : "error",
    "typescript/prefer-namespace-keyword"           : "error",
    "typescript/triple-slash-reference"             : "error",
    "typescript/array-type"                         : [
      "error",
      {
        default: "array-simple",
      },
    ],
    "typescript/ban-tslint-comment"          : "error",
    "typescript/class-literal-property-style": [
      "error",
      "fields",
    ],
    "typescript/consistent-generic-constructors": [
      "error",
      "constructor",
    ],
    "typescript/consistent-indexed-object-style": [
      "error",
      "record",
    ],
    "typescript/consistent-type-assertions": [
      "error",
      {
        assertionStyle             : "as",
        objectLiteralTypeAssertions: "allow-as-parameter",
      },
    ],
    "typescript/consistent-type-definitions": [
      "error",
      "interface",
    ],
    "typescript/consistent-type-exports": [
      "error",
      {
        fixMixedExportsWithInlineTypeSpecifier: true,
      },
    ],
    "typescript/consistent-type-imports": [
      "error",
      {
        prefer  : "type-imports",
        fixStyle: "inline-type-imports",
      },
    ],
    "typescript/explicit-function-return-type": [
      "error",
      {
        allowExpressions                                    : true,
        allowTypedFunctionExpressions                       : true,
        allowHigherOrderFunctions                           : true,
        allowDirectConstAssertionInArrowFunctions           : true,
        allowConciseArrowFunctionExpressionsStartingWithVoid: true,
      },
    ],
    "typescript/explicit-member-accessibility"  : "error",
    "typescript/explicit-module-boundary-types" : "error",
    "typescript/method-signature-style"         : ["error", "method"],
    "typescript/no-array-delete"                : "error",
    "typescript/no-confusing-non-null-assertion": "error",
    "typescript/no-confusing-void-expression"   : [
      "error",
      {
        ignoreArrowShorthand: true,
        ignoreVoidOperator  : true,
      },
    ],
    "typescript/no-duplicate-type-constituents"              : "error",
    "typescript/no-invalid-void-type"                        : "error",
    "typescript/no-meaningless-void-operator"                : "warn",
    "typescript/no-mixed-enums"                              : "error",
    "typescript/no-non-null-asserted-nullish-coalescing"     : "error",
    "typescript/no-unnecessary-condition"                    : "error",
    "typescript/no-unnecessary-parameter-property-assignment": "error",
    "typescript/no-unnecessary-qualifier"                    : "error",
    "typescript/no-unnecessary-template-expression"          : "error",
    "typescript/no-unnecessary-type-arguments"               : "error",
    "typescript/no-unnecessary-type-parameters"              : "error",
    "typescript/no-unsafe-enum-comparison"                   : "error",
    "typescript/no-unsafe-type-assertion"                    : "error",
    "typescript/no-unsafe-unary-minus"                       : "error",
    "typescript/no-useless-default-assignment"               : "error",
    "typescript/no-useless-empty-export"                     : "error",
    "typescript/non-nullable-type-assertion-style"           : "error",
    "typescript/prefer-find"                                 : "error",
    "typescript/prefer-for-of"                               : "error",
    "typescript/prefer-function-type"                        : "error",
    "typescript/prefer-includes"                             : "error",
    "typescript/prefer-nullish-coalescing"                   : "error",
    "typescript/prefer-optional-chain"                       : "error",
    "typescript/prefer-readonly"                             : "error",
    "typescript/prefer-reduce-type-parameter"                : "error",
    "typescript/prefer-return-this-type"                     : "error",
    "typescript/prefer-string-starts-ends-with"              : [
      "error",
      {
        allowSingleElementEquality: "always",
      },
    ],
    "typescript/promise-function-async"    : "error",
    "typescript/require-array-sort-compare": [
      "error",
      {
        ignoreStringArrays: true,
      },
    ],
    "typescript/switch-exhaustiveness-check": [
      "error",
      {
        allowDefaultCaseForExhaustiveSwitch: true,
        requireDefaultForNonUnion          : true,
        considerDefaultExhaustiveForUnions : true,
      },
    ],
    "typescript/unified-signatures": [
      "error",
      {
        ignoreDifferentlyNamedParameters: true,
      },
    ],
    "typescript/only-throw-error": "error",
    "typescript/return-await"    : [
      "error",
      "in-try-catch",
    ],
  },
  overrides: [
    {
      files: [
        "**/*.ts",
        "**/*.tsx",
        "**/*.mts",
        "**/*.cts",
      ],
      rules: {
        "constructor-super"           : "off",
        "getter-return"               : "off",
        "no-class-assign"             : "off",
        "no-const-assign"             : "off",
        "no-dupe-class-members"       : "off",
        "no-dupe-keys"                : "off",
        "no-func-assign"              : "off",
        "no-import-assign"            : "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls"                : "off",
        "no-redeclare"                : "off",
        "no-setter-return"            : "off",
        "no-this-before-super"        : "off",
        "no-undef"                    : "off",
        "no-unreachable"              : "off",
        "no-unsafe-negation"          : "off",
        "no-with"                     : "off",
        "prefer-const"                : [
          "error",
          {
            destructuring: "all",
          },
        ],
        "prefer-spread": "error",
      },
    },
  ],
});
